local highlights = {
		Normal = {fg = c.fg, bg = c.bg, },
		SignColumn = {bg = c.bg, },
		MsgArea = {fg = c.fg, bg =  c.bg, },
		ModeMsg = {fg = c.fg, bg = c.bg, },
		MsgSeparator = {fg = c.fg, bg = c.bg, },
		SpellBad = {fg = c.light_red, style = "underline", },
		SpellCap = {fg = c.yellow, style = "underline", },
		SpellLocal = {fg = c.green, style = "underline", },
		SpellRare = {fg = c.purple, style = "underline", },
		NormalNC = {fg = c.fg, bg = c.bg, },
		Pmenu = {fg = c.light_gray, bg = c.tree_gray, },
		PmenuSel = {bg = c.ui2_blue, },
		WildMenu = {fg = c.fg, bg = c.ui2_blue, },
		CursorLineNr = {fg = c.light_gray, style = "bold", },
		Comment = {fg = c.gray, style = "italic", },
		Folded = {fg = c.accent, bg = c.alt_bg, },
		FoldColumn = {fg = c.accent, bg = c.alt_bg, },
		LineNr = {fg = c.gray, },
		FloatBoder = {fg = c.gray, bg = c.alt_bg, },
		Whitespace = {fg = c.bg, },
		VertSplit = {fg = c.bg, bg = c.gray, },
		CursorLine = {bg = c.dark, },
		CursorColumn = {bg = c.dark, },
		ColorColumn = {bg = c.dark, },
		NormalFloat = {bg = c.dark, },
		Visual = {bg = c.ui_blue, },
		VisualNOS = {bg = c.alt_bg, },
		WarningMsg = {fg = c.error_red, bg = c.bg, },
		DiffAdd = {fg = c.alt_bg, bg = c.sign_add, },
		DiffChange = {fg = c.alt_bg, bg = c.sign_change, style = "underline", },
		DiffDelete = {fg = c.alt_bg, bg = c.sign_delete, },
		QuickFixLine = {bg = c.ui2_blue, },
		PmenuSbar = {bg = c.alt_bg, },
		PmenuThumb = {bg = c.gray, },
		MatchWord = {style = "underline", },
		MatchParen = {fg = c.hint_blue, bg = c.bg, style = "underline", },
		MatchWordCur = {style = "underline", },
		MatchParenCur = {style = "underline", },
		Cursor = {fg = c.cursor_fg, bg = c.cursor_bg, },
		lCursor = {fg = c.cursor_fg, bg = c.cursor_bg, },
		CursorIM = {fg = c.cursor_fg, bg = c.cursor_bg, },
		TermCursor = {fg = c.cursor_fg, bg = c.cursor_bg, },
		TermCursorNC = {fg = c.cursor_fg, bg = c.cursor_bg, },
		Conceal = {fg = c.accent, },
		Directory = {fg = c.blue, },
		SpecialKey = {fg = c.blue, style = "bold", },
		Title = {fg = c.blue, style = "bold", },
		ErrorMsg = {fg = c.error_red, bg = c.bg, style = "bold", },
		Search = {fg = c.light_gray, bg = c.search_orange, },
		IncSearch = {fg = c.search_blue, bg = c.light_gray, },
		Substitute = {fg = c.light_gray, bg = c.search_orange, },
		MoreMsg = {fg = c.orange, },
		Question = {fg = c.orange, },
		EndOfBuffer = {fg = c.bg, },
		NonText = {fg = c.bg, },
		Variable = {fg = c.light_blue, },
		String = {fg = c.orange, },
		Character = {fg = c.orange, },
		Constant = {fg = c.vivid_blue, },
		Number = {fg = c.light_green, },
		Boolean = {fg = c.blue, },
		Float = {fg = c.light_green, },
		Identifier = {fg = c.light_blue, },
		Function = {fg = c.yellow, },
		Operator = {fg = c.fg, },
		Type = {fg = c.cyan, },
		StorageClass = {fg = c.blue, },
		Structure = {fg = c.blue, },
		Typedef = {fg = c.blue, },
		Keyword = {fg = c.blue, },
		Statement = {fg = c.purple, },
		Conditional = {fg = c.blue, },
		Repeat = {fg = c.purple, },
		Label = {fg = c.purple, },
		Exception = {fg = c.purple, },
		Include = {fg = c.purple, },
		PreProc = {fg = c.purple, },
		Define = {fg = c.purple, },
		Macro = {fg = c.purple, },
		PreCondit = {fg = c.purple, },
		Special = {fg = c.orange, },
		SpecialChar = {fg = c.white, },
		Tag = {fg = c.blue, },
		Debug = {fg = c.red, },
		Delimiter = {fg = c.gray, },
		SpecialComment = {fg = c.gray, },
		Underlined = {style = "underline", },
		Bold = {style = "bold", },
		Italic = {style = "italic", },
		Ignore = {fg = c.cyan, bg = c.bg, style = "bold", },
		Todo = {fg = c.magenta, bg = c.bg, style = "bold", },
		Error = {fg = c.error_red, bg = c.bg, style = "bold", },
		TabLine = {fg = c.light_gray, bg = c.bg, },
		TabLineSel = {fg = c.white, bg = c.bg, },
		TabLineFill = {fg = c.alt_bg, bg = c.alt_bg, },
}

return highlights

